local wrapper = {}

wrapper.inherits_from = "PVInstance"

wrapper.properties = {
	"Size",
	"Position",
	"CFrame",
	"BrickColor",
	"Color",
	"TopSurface",
	"BottomSurface",
	"LeftSurface",
	"RightSurface",
	"FrontSurface",
	"BackSurface",
	"Locked",
	"Anchored",
	"CanCollide",
	"Material",
	"Transparency",
	"Rotation",
	"Reflectance",
	"CanTouch",
	"CanQuery",
	"AudioCanCollide",
	"BackParamA",
	"BackParamB",
	"FrontParamA",
	"FrontParamB",
	"TopParamA",
	"TopParamB",
	"BottomParamA",
	"BottomParamB",
	"LeftParamA",
	"LeftParamB",
	"RightParamA",
	"RightParamB",
	"BottomSurfaceInput",
	"CastShadow",
	"CenterOfMass",
	"CollisionGroupId",
	"CurrentPhysicalProperties",
	"CustomPhysicalProperties",
	"Elasticity",
	"EnableFluidForces",
	"ExtentsCFrame",
	"ExtentsSize",
	"Friction",
	"FrontSurfaceInput",
	"TopSurfaceInput",
	"BackSurfaceInput",
	"LeftSurfaceInput",
	"RightSurfaceInput",
	"LocalTransparencyModifier",
	"Massless",
	"MaterialVariant",
	"PivotOffset",
	"Mass",
	"ReceiveAge",
	"ResizeIncrement",
	"ResizeableFaces",
	"RootPriority",
	"RotVelocity",
	"Orientation",
	"SpecificGravity",
	"Velocity",
	"brickColor"
}

wrapper.methods = {
	"AngularAccelerationToTorque",
	"ApplyAngularImpulse",
	"ApplyImpulse",
	"ApplyImpulseAtPosition",
	"BreakJoints",
	"CanCollideWith",
	"CanSetNetworkOwnership",
	"GetClosestPointOnSurface",
	"GetConnectedParts",
	"GetJoints",
	"GetMass",
	"GetNetworkOwner",
	"GetNetworkOwnershipAuto",
	"GetNoCollisionConstraints",
	"GetRenderCFrame",
	"GetRootPart",
	"GetTouchingParts",
	"GetVelocityAtPosition",
	"IsGrounded",
	"MakeJoints",
	"Resize",
	"SetNetworkOwner",
	"SetNetworkOwnershipAuto",
	"TorqueToAngularAcceleration",
	"breakJoints",
	"getMass",
	"makeJoints",
	"resize"
}

wrapper.events = {
	"LocalSimulationTouched",
	"OutfitChanged",
	"StoppedTouching",
	"Touched",
	"TouchEnded"
}

return wrapper