local wrapper = {}

wrapper.inherits_from = "Instance"

wrapper.properties = {
	"AutoJumpEnabled",
	"AutoRotate",
	"AutomaticScalingEnabled",
	"BreakJointsOnDeath",
	"CameraOffset",
	"DisplayDistanceType",
	"DisplayName",
	"EvaluateStateMachine",
	"FloorMaterial",
	"Health",
	"HealthDisplayDistance",
	"HealthDisplayType",
	"HipHeight",
	"Jump",
	"JumpHeight",
	"JumpPower",
	"LeftLeg",
	"MaxHealth",
	"MaxSlopeAngle",
	"MoveDirection",
	"NameDisplayDistance",
	"NameOcclusion",
	"PlatformStand",
	"RequiresNeck",
	"RigType",
	"RightLeg",
	"RootPart",
	"SeatPart",
	"Sit",
	"TargetPoint",
	"Torso",
	"UseJumpPower",
	"WalkSpeed",
	"WalkToPart",
	"WalkToPoint",
	"maxHealth"
}

wrapper.methods = {
	"AddAccessory",
	"AddCustomStatus",
	"AddStatus",
	"ApplyDescription",
	"ApplyDescriptionReset",
	"BuildRigFromAttachments",
	"ChangeState",
	"EquipTool",
	"GetAccessories",
	"GetAppliedDescription",
	"GetBodyPartR15",
	"GetLimb",
	"GetMoveVelocity",
	"GetPlayingAnimationTracks",
	"GetState",
	"GetStateEnabled",
	"GetStatuses",
	"HasCustomStatus",
	"HasStatus",
	"LoadAnimation",
	"Move",
	"MoveTo",
	"PlayEmote",
	"RemoveAccessories",
	"RemoveCustomStatus",
	"RemoveStatus",
	"ReplaceBodyPartR15",
	"SetStateEnabled",
	"TakeDamage",
	"UnequipTools",
	"loadAnimation",
	"takeDamage"
}

wrapper.events = {
	"AnimationPlayed",
	"ApplyDescriptionFinished",
	"Climbing",
	"CustomStatusAdded",
	"CustomStatusRemoved",
	"Died",
	"FallingDown",
	"FreeFalling",
	"GettingUp",
	"HealthChanged",
	"Jumping",
	"MoveToFinished",
	"PlatformStanding",
	"Ragdoll",
	"Running",
	"Seated",
	"StateChanged",
	"StateEnabledChanged",
	"StatusAdded",
	"StatusRemoved",
	"Strafing",
	"Swimming",
	"Touched"
}

return wrapper
